config/routes.rb
A::Application.routes.draw do

  root 'gadgets#index'
  resources :user_sessions
  resources :users
  resources :gadgets
  get 'login' => "user_sessions#new",      :as => :login
  get 'logout' => "user_sessions#destroy", :as => :logout

end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
  belongs_to :user
  has_many :images
  validates_presence_of :name
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gadget
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_authentic
  has_many :gadgets

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end

    def require_user
      logger.debug "ApplicationController::require_user"
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
    end

    def require_no_user
      logger.debug "ApplicationController::require_no_user"
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
       # redirect_to home_index_path
        return false
      end
    end

    def store_location
      #session[:return_to] = request.request_uri
    end

    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
  before_filter :require_user
  def index
    @gadgets = current_user.gadgets
    render :action => "gallery" if params[:type]=="gallery"
  end
  def new
    @gadget = Gadget.new
  end

  def create
    @gadget = current_user.gadgets.create(gadget_params)
    if @gadget
      params[:gadget][:images].each do |image|
        @gadget.images.create(:image=>image)
      end if params[:gadget][:images]
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  def destroy
    Gadget.find(params[:id]).destroy
    redirect_to :action=>:index
  end

  private
  def gadget_params
    params.require(:gadget).permit(:name)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_user,  :only => :destroy

  def new
    redirect_to "/gadgets" if current_user
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default "/"
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default new_user_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_user,  :only => [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
     redirect_to "/gadgets"
    else
     render :action => :new
    end
  end

  private
  def user_params
   params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gadgets/gallery.html.erb
<% @gadgets.each do |gadget| %>
  <div style="float:left;width:130px;">
    <%= image_tag gadget.images.first.image.url(:thumb) %>
    <br/><%= gadget.name %>
  </div>
<% end %>
<div style="clear:both;"></div>
<hr/>
<%= link_to "New Gadget", :action=>:new %>

app/views/gadgets/index.html.erb
<% @gadgets.each do |gadget| %>
  <h3><%= gadget.name %></h3><%= link_to "Delete", gadget_path(gadget), :method=>:delete, :confirm=>"Are you sure?" %>
  <p>
    <% gadget.images.map{|c| c.image.url(:medium)}.each do |url| %>
      <%= image_tag url %>
    <% end %>
  </p>
  <hr />
<% end %>
<hr/>
<%= link_to "New Gadget", :action=>:new %>

app/views/gadgets/new.html.erb
<h2>New Gadget</h2>

<%= render "shared/error_messages", :target => @gadget %>

<%= form_for @gadget do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, :class=>"form-control", :placeholder=>"Name" %>
  <p>
  <p>
    <%= f.file_field :images, :multiple=>true %>
  </p>
  <br/>
  <%= f.submit "Add" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
<%= link_to "Gadget Gallery", :controller=>:gadgets, :action=>:index, :type=>:gallery %>
<%= link_to "Gadget List", :controller=>:gadgets, :action=>:index %>

<%= link_to "Logout", "/logout" %>
<% else %>
<%= link_to "Login", :action=>:new, :controller=>:user_sessions %>
<%= link_to "Register", :controller=>:users, :action=>:new %>

<% end %>
<hr/>
<%= yield %>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div id="errorExplanation">
    <h5><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h5>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= form_for @user_session, :as => :user_session, :url => { :action => "create" } do |f| %>
  <%= render "shared/error_messages", :target => @user_session %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email, :class=>"form-control", :placeholder=>"Email" %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password, :class=>"form-control", :placeholder=>"Password" %>
  </p>
  <%= f.submit "Login", :class=>"btn btn-default" %>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= render "shared/error_messages", :target => @user %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, :class=>"form-control", :placeholder=>"Name" %>
  <p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email, :placeholder=>"Email" %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password, :placeholder=>"Password" %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :placeholder=>"Password Confirmation" %>
  </p>

  <%= f.submit "Sign Up" %>

<% end %>